
-- Reset Database: Hapus tabel lama jika ada sebelum membuat yang baru
DROP TABLE IF EXISTS stats_growth CASCADE;
DROP TABLE IF EXISTS carousel CASCADE;
DROP TABLE IF EXISTS proker CASCADE;
DROP TABLE IF EXISTS dana CASCADE;
DROP TABLE IF EXISTS buku CASCADE;
DROP TABLE IF EXISTS berita CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS pengaduan CASCADE;
DROP TABLE IF EXISTS admins CASCADE;

CREATE TABLE IF NOT EXISTS admins (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL
);


CREATE TABLE IF NOT EXISTS pengaduan (
    id SERIAL PRIMARY KEY,
    identitas VARCHAR(100) NOT NULL,
    nim VARCHAR(20) NOT NULL,
    kontak VARCHAR(20) NOT NULL,
    jurusan VARCHAR(100) NOT NULL,
    fakultas VARCHAR(100) NOT NULL,
    subject VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    file_path VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS berita (
    id SERIAL PRIMARY KEY,
    judul VARCHAR(255) NOT NULL,
    konten TEXT NOT NULL,
    bidang VARCHAR(50),
    file_path VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS events (
    id SERIAL PRIMARY KEY,
    judul VARCHAR(255) NOT NULL,
    deskripsi TEXT,
    tanggal DATE NOT NULL,
    lokasi VARCHAR(255),
    file_path VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS buku (
    id SERIAL PRIMARY KEY,
    judul VARCHAR(255) NOT NULL,
    penulis VARCHAR(100),
    file_path VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dana (
    id SERIAL PRIMARY KEY,
    judul VARCHAR(255) NOT NULL,
    deskripsi TEXT,
    amount NUMERIC,
    file_path VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS proker (
    id SERIAL PRIMARY KEY,
    nama_proker VARCHAR(255) NOT NULL,
    departemen_id VARCHAR(50),
    deskripsi TEXT,
    file_path VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS carousel (
    id SERIAL PRIMARY KEY,
    judul VARCHAR(255),
    file_path VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stats_growth (
    id SERIAL PRIMARY KEY,
    bulan VARCHAR(10) UNIQUE NOT NULL,
    jumlah INTEGER NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
